name: Go

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
      id: go
    
    - name: Extract tag
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Replace __TAG__ in main.go
      run: sed -i "s/__TAG__/${{ env.TAG }}/g" main.go
    
    - name: Replace __TAG__ in makefile
      run: sed -i "s/__TAG__/${{ env.TAG }}/g" Makefile

    - name: Test
      run: go mod tidy && make test
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
